version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.12.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.12.0
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.12.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8080:8080
            - 5000:5000
        volumes:
          - ./logstash:/usr/share/logstash/pipeline
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork  
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        command: ["--config.file=/etc/prometheus/prometheus.yml"]
        volumes: 
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
        - "9090:9090"
        depends_on:
        - elasticsearch
        - kibana
        networks:
        - elknetwork   
    mongodb:
        image : tutum/mongodb
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        - MONGODB_USER="admin"
        - MONGODB_PASS="xpt9"
        - MONGODB_DATABASE="mydatabase"
        ports:
        - 27017:27017
        - 28017:28017
        depends_on:
        - elasticsearch
        - kibana
        networks:
        - elknetwork   
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.12.0
        container_name: metricbeat
        #command: "metricbeat setup -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=[\"elasticsearch:9200\"]"
        environment:
        - setup.kibana.host=kibana:5601
        - output.elasticsearch.hosts=["elasticsearch:9200"]
        volumes: 
        - ./metricbeat/prometheus.yml:/usr/share/metricbeat/modules.d/prometheus.yml
        - ./metricbeat/mongodb.yml:/usr/share/metricbeat/modules.d/mongodb.yml
        #- ./metricbeat/kubernetes.yml:/usr/share/metricbeat/modules.d/kubernetes.yml
        depends_on:
          - mongodb
          - prometheus
        networks:
          - elknetwork    
networks:
    elknetwork:
        driver: bridge