version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.12.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.12.0
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.12.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8080:8080
            - 5000:5000
            - 5044:5044
        volumes:
          - ./logstash:/usr/share/logstash/pipeline
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork 
    mongodb:
        image : tutum/mongodb
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        - MONGODB_USER="admin"
        - MONGODB_PASS="xpt9"
        - MONGODB_DATABASE="mydatabase"
        ports:
        - 27017:27017
        - 28017:28017
        depends_on:
        - elasticsearch
        - kibana
        networks:
        - elknetwork   
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.12.0
        container_name: metricbeat
        environment:
        - setup.kibana.host=kibana:5601
        - output.elasticsearch.hosts=["elasticsearch:9200"]
        volumes: 
        - ./metricbeat/mongodb.yml:/usr/share/metricbeat/modules.d/mongodb.yml
        - ./metricbeat/kubernetes.yml:/usr/share/metricbeat/modules.d/kubernetes.yml
        depends_on:
          - mongodb
        networks:
          - elknetwork     
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.12.0
        container_name: filebeat
        volumes: 
        - ./logs-services:/usr/share/filebeat/logs
        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
        depends_on:
        - metricbeat
        networks:
        - elknetwork    
networks:
    elknetwork:
        driver: bridge